"" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 3
# Current Theme: gruvbox

[[blocks]]
alignment = "left"
type = "prompt"

  [[blocks.segments]]
  background = "#282828"
  foreground = "#ebdbb2"
  leading_diamond = "╭─"
  style = "diamond"
  template = "{{ .UserName }}@{{ .HostName }}"
  type = "shell"

  [[blocks.segments]]
  background = "#d65d0e"
  foreground = "#ebdbb2"
  powerline_symbol = ""
  style = "powerline"
  template = "{{ .Path }} "
  type = "path"
    [blocks.segments.properties]
    folder_icon = "  "
    home_icon = " "
    style = "full"

  [[blocks.segments]]
  background = "#98971a"
  foreground = "#ebdbb2"
  powerline_symbol = ""
  style = "powerline"
  template = "{{ .UpstreamIcon }}{{ .HEAD }}{{ if .BranchStatus }} {{ .BranchStatus }}{{ end }}"
  type = "git"
    [blocks.segments.properties]
    branch_icon = " "
    fetch_status = true
    fetch_upstream_icon = true

  [[blocks.segments]]
  background = "#458588"
  foreground = "#ebdbb2"
  style = "diamond"
  template = "  {{ .FormattedMs }}⠀"
  trailing_diamond = ""
  type = "executiontime"

[[blocks]]
alignment = "right"
type = "prompt"

  [[blocks.segments]]
  background = "#b16286"
  foreground = "#ebdbb2"
  leading_diamond = ""
  style = "diamond"
  template = " {{ if .WSL }}WSL at {{ end }}{{.Icon}} "
  type = "os"
    [blocks.segments.properties]
    linux = ""
    macos = ""
    windows = ""

  [[blocks.segments]]
  type = "text"
  style = "plain"
  background = "#282828"
  foreground = "#ebdbb2"
  template = "On"

  [[blocks.segments]]
  background = "#d65d0e"
  foreground = "#ebdbb2"
  style = "diamond"
  template = " {{ .Name }} "
  type = "shell"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  foreground = "#b16286"
  style = "plain"
  template = "╰─"
  type = "text"

  [[blocks.segments]]
  foreground = "#458588"
  style = "plain"
  template = " "
  type = "status"
    [blocks.segments.properties]
    always_enabled = true
